kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment
  namespace: utilityapp
  labels:
    app: app-deploy
spec:
  selector:
    matchLabels:
      app: utilityapp
  template:
    metadata:
      labels:
        app: utilityapp
    spec: 
      containers:
        - name: app
          image: uapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
           
          envFrom:
            - configMapRef:
                name: config-map 
            - secretRef:
                name: app-secrets
                name: docker-secrets
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
          startupProbe:
            httpGet:
              path: /metric
              port: 8081
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /metric
              port: 8081
            timeoutSeconds: 5
            periodSeconds: 20
            initialDelaySeconds: 15
            failureThreshold: 15
          readinessProbe: 
            httpGet:
              path: /metric
              port: 8081
            timeoutSeconds: 5
            periodSeconds: 30
            initialDelaySeconds: 20
            failureThreshold: 15
            
