kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: app-scale
  namespace: utilityapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

  behavior:
    scaleUp:
        stabilizationWindowSeconds: 30
        policies:
          - type: Pods
            value: 1
            periodSeconds: 30

    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 40

