name: dependency scan
on:
  workflow_call:
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup-python
        uses: actions/setup-python@5
        with:
          python-version: "3.12"
      - name: install audit
        run: pip install pip-audit  
      - name: audit
        run: pip-audit -r requirements.txt
  