name: deploy to server
on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: SSH to prod server and install Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ vars.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Installing Docker and Compose on EC2..."
            sudo apt-get install -y docker.io && sudo apt-get install -y docker-compose-v2
            sudo usermod -aG docker $USER
            mkdir -p ~/devopsi
      - name: copy docker compose file
        uses: appleboy/scp-action@v1
        with:
           username: ${{ vars.SSH_USER }}
           host: ${{ secrets.SSH_HOST }}
           key: ${{ secrets.KEY}}
           source: docker-compose.yml
           target: ~/devopsi
      - name: ssh to prod server and run
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ vars.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.KEY}}
          scripts: |
            echo " running web"
            export DOCKERHUB_USER=${{ vars.DOCKERUSER }}
            export DOCKER_TAG=${{ github.sha }}
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ vars.DOCKERUSER }} --password-stdin
            cd ~/devopsi $$ docker compose down $$ docker compose up -d --build --force-recreate --pull always
