name: DevSecOps End To End Pipeline

on: 
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrets:
        uses: ./.github/workflows/secrets.yml
        secrets: inherit
    
    dependency:
        uses: ./.github/workflows/dependency.yml
    
    docker-lint:
        uses: ./.github/workflows/docker-lint.yml
    
    build:
        needs: [code-quality, secrets, dependency, docker-lint]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit
    deploy:
      needs: [trivy]
      uses: ./.github/workflows/deploy-to-server.yml
      secrets: inherit
