name: docker build and push
on:
  workflow_call:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
             ${{ vars.DOCKERHUB_USER }}/app:${{ github.sha}}
           
