name: docker build and push
on:
  workflow_call:
jobs:
  build and push:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: docker login
      uses: docker/login@v3
      with:
        username: ${{vers.DOCKERUSER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
            ${{ vars.DOCKERHUB_USER }}/app:latest
            ${{ vars.DOCKERHUB_USER }}/app:${{ github.sha}}
           