name: secret-scan
on:
  workflow_call
jobs:
  secrets-scan:
  runs-on: ubuntu-latest
  steps:
    - name: check code
      uses: actions/checkout@v4
      with:
        fetch-dept: 0
    - name: secret scan
      uses: gitleaks/gitleaks-actions@v2
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        